[package]
name = "NN"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
ndarray = "0.15"
rayon = "1.5"
rand = "0.8"
futures = "0.3"

[[bin]]
name = "NN"
path = "main.rs"
